learning_rate: 0.0001
batch_size: 32
num_epochs: 50
warmup_epochs: 10
part_selection_epochs: 15
relation_learning_epochs: 15
fine_tuning_epochs: 10
weight_decay: 0.01
momentum: 0.9
num_classes: 2
image_size: 224
train_data_path: "path/to/train_data"
pretrained_model_path: "path/to/pretrained/model"
save_model_path: "path/to/save/model"
log_dir: "path/to/logs"
seed: 42
augmentation:
  random_crop: true
  random_flip: true
  normalize: true
  color_jitter: true
  rotation: true